# Generated by Django 2.1.5 on 2019-12-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='est_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='fin_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='requiremnets',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='rtrn_date',
            field=models.DateTimeField(null=True),
        ),
    ]
